# Generated by Django 5.2.7 on 2025-10-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='colecao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='wishList',
            field=models.BooleanField(default=False),
        ),
    ]
