# Generated by Django 5.2.7 on 2025-10-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_colecao_game_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='api_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='img',
            field=models.ImageField(default=2, upload_to='./imgs_dados'),
            preserve_default=False,
        ),
    ]
