# Generated by Django 5.2.7 on 2025-10-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_api_id_game_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='discount',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prices',
            name='discountedPrice',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
