# Generated by Django 5.2.7 on 2025-10-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_prices_discount_prices_discountedprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='img',
            field=models.ImageField(upload_to='./imgs_dados/'),
        ),
    ]
